### ISSUE TITLE
Excesive calls to ensureIndexes() for any DB usage

### ISSUE THREAD

**Issue by alejavigo** [seedstack/mongodb-addon#15]
Morhpia ensureIndexes() method is being called in every Datastore creation , and that meand for every injection of DB Repositories or DB usage. That will send createIndex commands in every use of the DB for all the fields of entities annotated as @Indexed. This will be a lot of duplicated commands that the DB will ignore quickly, but can affect greatly if there is high latency between App and DB.
EnsureIndexes is only needed and should be called just once at the loading of the app and/or plugin.

File: org.seedstack.mongodb.morphia.internal.DatastoreFactory
Method: createDatastore

**Comment by adrienlauer** [comment]
Fixed by #14 in latest version. To be backported to 3.0.x.

**Comment by adrienlauer** [comment]
Backported in 3.0.3 through commit 57d3450ab2f4434fc644cbd7fef33570cf5c5d87
